queries:
- include: "*"
- exclude: "cpp/class-many-fields"
- exclude: "cpp/long-switch"
- exclude: "cpp/trivial-switch"

extraction:
  python:
    python_setup:
      version: "3"
    index:
      include: "tools/cFS-GroundSystem"
      exclude: "tools/cFS-GroundSystem/**/Ui_*"
  cpp:
    index:
      build_command:
      - "cp cfe/cmake/Makefile.sample Makefile"
      - "cp -r cfe/cmake/sample_defs sample_defs"
      - "make OMIT_DEPRECATED=true prep"
      - "make"

